import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NoteProvider } from "@/context/NoteContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="pt-3">
          <NoteProvider>{children}</NoteProvider>
        </div>
      </body>
    </html>
  );
}
